name: "❓ Ask a Question"
description: Ask a question about TIDAL.
title: "❓ [QUESTION] - <title>"
labels:
  - "question"
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <img src="https://user-images.githubusercontent.com/24313187/216609683-bac9e15c-6860-4441-a9ae-936f81940b1b.png" alt="TIDAL Logo">
          <br>
          <em><a href="https://doi.org/10.1093/ije/dyaf095">TIDAL's Paper</a>—<a href="https://tidal-modelling.github.io/">TIDAL's Documentation</a>.</em>
        </p>
  - type: checkboxes
    id: checks
    attributes:
      label: "Before Submitting"
      description: Please confirm the following to help us answer your question efficiently.
      options:
        - label: I have checked the documentation and existing issues.
          required: true
  - type: textarea
    id: question
    attributes:
      label: "Question"
      description: Please provide a clear and concise question.
      placeholder: "Hint: ‘brevity is the soul of wit’, Hamlet — by William Shakespeare"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: Provide any additional context or details that might help answer your question.
      placeholder: "Hint: Optional, e.g., code snippets, error messages, etc."
    validations:
      required: false
  - type: input
    id: project-area
    attributes:
      label: "Project Area"
      description: Specify the area of TIDAL your question relates to.
      placeholder: "Hint: Optional, e.g., R Shiny App, R Package, Desktop App, Docker, Data Analysis, etc."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Security Note:** Please do not share sensitive information such as personal data, confidential project details, or sensitive datasets in this question,